### ISSUE TITLE
not an issue but a request

### ISSUE THREAD

**Issue by aeugurauhhr** [bodnjenie14/Project_-bo4_Launcher#12]
For megalomaniacs like me and considering the fact that Lucy mod menu cannot be injected on this client can you please add a separate Cheaty Options menu that has stuff like God mode and etc? Can you also make it so that game options can be saved coz I find it a bit of a hassle to put in the same settings I want each time I reload the game. I don't wanna waste like 80+ dollars on a game just for a mod menu too. Thanks!

**Comment by bodnjenie14** [comment]
mods can be used on the client with ease 

https://shield-bo4.gitbook.io/document

**Comment by aeugurauhhr** [comment]
Oh, seems I found a mod menu on the Released Mods section. I might try that out and see if it works.

**Comment by bodnjenie14** [comment]
ill close now then enjoy
